### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by martinfpas** [csrocha/odoo_fpoc#1]
Hola Cristian, instale los modulos

odoo_fpoc
l10n_ar_fpoc
l10n_ar_fpoc_pos

y tengo en una virtual de vbox el emulador fiscal con el COM2 virtual.

Fui hasta Configuracion > Fiscal Printer > Crear

ahi trate de darle de alta con los siguientes datos (no vi ningun instructivo, asi que solo deduje los campos)

![c_rocha_fisca_printer_error](https://cloud.githubusercontent.com/assets/5508133/5663267/7f05eea0-9723-11e4-973a-1dee91f4fe7f.png)

Cuando trato de guardar me da el siguiente error:

2015-01-08 03:32:55,246 2883 ERROR test openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
File "/vagrant/odoo/openerp/http.py", line 524, in handle_exception
return super(JsonRequest, self).handle_exception(exception)
File "/vagrant/odoo/openerp/http.py", line 545, in dispatch
result = self._call_function(*self.params)
File "/vagrant/odoo/openerp/http.py", line 301, in _call_function
return checked_call(self.db, *args, *kwargs)
File "/vagrant/odoo/openerp/service/model.py", line 113, in wrapper
return f(dbname, args, *kwargs)
File "/vagrant/odoo/openerp/http.py", line 298, in checked_call
return self.endpoint(a, *kw)
File "/vagrant/odoo/openerp/http.py", line 761, in __call
return self.method(args, *kw)
File "/vagrant/odoo/openerp/http.py", line 394, in response_wrap
response = f(args, *kw)
File "/vagrant/odoo/addons/web/controllers/main.py", line 949, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/vagrant/odoo/addons/web/controllers/main.py", line 941, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, args, *kwargs)
File "/vagrant/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/vagrant/odoo/openerp/api.py", line 332, in old_api
result = method(recs, args, *kwargs)
File "/vagrant/odoo/openerp/models.py", line 4007, in create
record = self.browse(self._create(old_vals))
File "/vagrant/odoo/openerp/api.py", line 235, in wrapper
return new_api(self, args, *kwargs)
File "/vagrant/odoo/openerp/api.py", line 464, in new_api
result = method(self._model, cr, uid, args, *kwargs)
File "/vagrant/odoo/openerp/models.py", line 4192, in _create
result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
File "/vagrant/odoo/openerp/osv/fields.py", line 1384, in set
self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
File "/vagrant/odoo/addons/fpoc/epson.py", line 72, in _put_field
lines = field_value.split('\n')[:len(_footer_lines)]
AttributeError: 'bool' object has no attribute 'split'

Muchas gracias
Saludos
Martin

**Comment by csrocha** [comment]
@martinfpas , gracias por copiar el issue. Podrías ver si ocurre el mismo error ahora usando el branch issue_1?

**Comment by martinfpas** [comment]
Parece el mismo resultado. Limpie la consola antes de loguearme. 
Te copio toda la consola completa, perdón si se repite el error.

Te adjunto cambien una captura del log expandido.

 [SES] Start background login.
background.js:46 [SES] Creating the session.
background.js:71 [SES] Session error. Forget session_id.
extensions::binding:471 chrome.appViewInternal is not available: 'appViewInternal' requires Google Chrome dev channel or newer, but this is the stable channel.
background.js:10 [FP] Pooling for printers
oerp.js:346 [SES] Updating printers.
tools.js:200 [PF] USB found end
3epson_ar.js:1611 EPSON: Constructor
extensions::uncaught_exception_handler:8 Error in response to serial.connect: TypeError: Cannot read property 'connectionId' of undefined
    at send (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:57:38)
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:503:36
    at alive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:102:9)
    at command (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:494:24)
    at _get_status (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:511:13)
    at get_status (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:1398:18)
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/tools.js:116:29
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:1618:37
    at Object.callback (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:44:21)
    at open (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:41:23)
    at epson_ar_open (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:1618:15)
    at declarePrinter (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/tools.js:114:35)
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/tools.js:207:13
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/async.js:111:13
    at _each (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/async.js:32:24)
extensions::sendRequest:82 Unchecked runtime.lastError while running serial.connect: Failed to connect to the port.
    at open (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:41:23)
    at epson_ar_open (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:1618:15)
    at declarePrinter (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/tools.js:114:35)
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/tools.js:207:13
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/async.js:111:13
    at _each (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/async.js:32:24)
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
epson_ar.js:303 Type  \*  not implemented
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
serial.js:26 ReceiveInfo:
serial.js:27 ObjectconnectionId: 1data: ArrayBuffer__proto__: Object
serial.js:28 Connection:
serial.js:29 Objectbitrate: 9600bufferSize: 4096connectionId: 1ctsFlowControl: falsedataBits: "eight"name: ""parityBit: "no"paused: falsepersistent: falsereceiveTimeout: 0sendTimeout: 0stopBits: "one"**proto**: Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 Object
serial.js:26 ReceiveInfo:
serial.js:27 Object
serial.js:28 Connection:
serial.js:29 undefined
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:30:50)
extensions::uncaught_exception_handler:8 Error in response to serial.send: RangeError: Offset is outside the bounds of the DataView
    at unpack (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:298:23)
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:435:64
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:408:61
    at Object.callback (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:64:21)
    at send (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:57:23)
    at sendACK (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:408:24)
    at local_callback (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/epson_ar.js:434:30)
    at receive (chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:89:21)
    at chrome-extension://abimneomlbfdbpmibmddbenoejjpdgmm/src/serial.js:96:22
epson_ar.js:447 EPSON: Device closed
background.js:49 Successful login.
oerp.js:41 Create spool  session_id=7311aa20314d3b4c0629d545b80b79df0b19893d

![impresora](https://cloud.githubusercontent.com/assets/5508133/5664004/681ea224-972b-11e4-95ca-0074bbe3ed4e.png)

**Comment by csrocha** [comment]
@martinfpas este último que enviaste es otro error y va en el otro repositorio. Por favor no mezclemos. Aquí estamos discutiendo sobre: AttributeError: 'bool' object has no attribute 'split'

**Comment by martinfpas** [comment]
Mis disculpas, tenes razón, 

1) Con la opción "Disconected" en esta versión no muestra la impresora: y tarda muchisimo (estimo que es por timeout)

 POST http://192.168.0.100:8069/longpolling/poll net::ERR_CONNECTION_RESET10ece11:730 send10ece11:700 jQuery.extend.ajax10ece11:1120 (anonymous function)10ece11:1118 genericJsonRpc10ece11:1120 openerp.jsonRpc10ece11:1132 (anonymous function)10ece11:249 (anonymous function)10ece11:243 fire10ece11:244 self.add10ece11:249 (anonymous function)10ece11:225 jQuery.extend.each10ece11:249 (anonymous function)10ece11:250 jQuery.extend.Deferred10ece11:249 promise.then10ece11:1129 openerp.Session.openerp.Class.extend.rpc7d5e815:4026 bus.Bus.openerp.Widget.extend.poll7d5e815:4026 (anonymous function)10ece11:249 (anonymous function)10ece11:243 fire10ece11:248 self.fireWith10ece11:249 self.fire10ece11:243 fire10ece11:248 self.fireWith10ece11:249 (anonymous function)10ece11:243 fire10ece11:248 self.fireWith10ece11:249 (anonymous function)10ece11:243 fire10ece11:248 self.fireWith10ece11:682 done10ece11:735 callback

2) Y si intento el Fiscal Printer > Create me da el mismo error (AttributeError: 'bool' object has no attribute 'split'), pero supongo que es lo esperable, y que no debería volver a intentar.

**Comment by csrocha** [comment]
Hola Martin,

si, el Disconected es el resultado de que el Serial no funciona. Estoy
revisando.

Saludos,
Cristian.

On Thu, Jan 8, 2015 at 12:15 PM, martinfpas notifications@github.com
wrote:

> Mis disculpas, tenes razón,
> 
> 1) Con la opción "Disconected" en esta versión no muestra la impresora: y
> tarda muchisimo (estimo que es por timeout)
> 
> POST http://192.168.0.100:8069/longpolling/poll
> net::ERR_CONNECTION_RESET10ece11:730 send10ece11:700
> jQuery.extend.ajax10ece11:1120 (anonymous function)10ece11:1118
> genericJsonRpc10ece11:1120 openerp.jsonRpc10ece11:1132 (anonymous
> function)10ece11:249 (anonymous function)10ece11:243 fire10ece11:244
> self.add10ece11:249 (anonymous function)10ece11:225
> jQuery.extend.each10ece11:249 (anonymous function)10ece11:250
> jQuery.extend.Deferred10ece11:249 promise.then10ece11:1129
> openerp.Session.openerp.Class.extend.rpc7d5e815:4026
> bus.Bus.openerp.Widget.extend.poll7d5e815:4026 (anonymous
> function)10ece11:249 (anonymous function)10ece11:243 fire10ece11:248
> self.fireWith10ece11:249 self.fire10ece11:243 fire10ece11:248
> self.fireWith10ece11:249 (anonymous function)10ece11:243 fire10ece11:248
> self.fireWith10ece11:249 (anonymous function)10ece11:243 fire10ece11:248
> self.fireWith10ece11:682 done10ece11:735 callback
> 
> 2) Y si intento el Fiscal Printer > Create me da el mismo error
> (AttributeError: 'bool' object has no attribute 'split'), pero supongo que
> es lo esperable, y que no debería volver a intentar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csrocha/odoo_fpoc/issues/1#issuecomment-69192652.

## 

Coop. de Trab. Moldeo Interactive Lmt.
Cristian Sebastian Rocha
Consultor Analista.
Bonpland 2363 Of 303
(C1425FWE) CABA, Argentina.
(+54-9-11).6800.0269
http://interactive.moldeo.coop

**Comment by aek** [comment]
El error original no ocurre con los cambios de la rama issue_1
