### ISSUE TITLE
No puedo instalar 

### ISSUE THREAD

**Issue by delatorremario** [csrocha/odoo_fpoc#3]
Buenos dias,
no he podido instalar el módulo
tengo la versión 8

Odoo
Odoo Server Error
Traceback (most recent call last):
  File "C:\odoo\Odoo8\server.\openerp\http.py", line 530, in _handle_exception
  File "C:\odoo\Odoo8\server.\openerp\http.py", line 567, in dispatch
  File "C:\odoo\Odoo8\server.\openerp\http.py", line 303, in _call_function
  File "C:\odoo\Odoo8\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\odoo\Odoo8\server.\openerp\http.py", line 300, in checked_call
  File "C:\odoo\Odoo8\server.\openerp\http.py", line 796, in __call__
  File "C:\odoo\Odoo8\server.\openerp\http.py", line 396, in response_wrap
  File "C:\odoo\Odoo8\server\openerp\addons\web\controllers\main.py", line 939, in call_button
  File "C:\odoo\Odoo8\server\openerp\addons\web\controllers\main.py", line 927, in _call_kw
  File "C:\odoo\Odoo8\server.\openerp\api.py", line 241, in wrapper
  File "C:\odoo\Odoo8\server.\openerp\api.py", line 393, in old_api
  File "C:\odoo\Odoo8\server.\openerp\api.py", line 397, in new_api
  File "C:\odoo\Odoo8\server\openerp\addons\base\module\wizard\base_module_update.py", line 15, in update_module
  File "C:\odoo\Odoo8\server.\openerp\api.py", line 239, in wrapper
  File "C:\odoo\Odoo8\server.\openerp\api.py", line 462, in new_api
  File "C:\odoo\Odoo8\server\openerp\addons\base\module\module.py", line 654, in update_list
  File "C:\odoo\Odoo8\server.\openerp\http.py", line 1298, in load_addons
  File "C:\odoo\Odoo8\server.\openerp\modules\module.py", line 80, in load_module
  File "C:\odoo\Odoo8\server\openerp\addons\fpoc__init__.py", line 3, in <module>
  File "C:\odoo\Odoo8\server\openerp\addons\fpoc\fiscal_printer.py", line 28, in <module>
  File "C:\odoo\Odoo8\server\openerp\addons\fpoc\controllers__init__.py", line 23, in <module>
  File "C:\odoo\Odoo8\server\openerp\addons\fpoc\controllers\main.py", line 30, in <module>
ImportError: No module named multiprocessing

**Comment by csrocha** [comment]
El módulo multiprocessing es standard de python y es lo que dice que falta. Estoy leyendo la [documentación](https://docs.python.org/2/library/multiprocessing.html#windows) y no veo que windows tenga problemas de importación. Que versión de Python tienes instalada.

**Comment by elgransan** [comment]
Hola estoy tratando de instalarlo en Odoo version 9 y también me devuelve un error en la instalación: 

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\http.py", line 643, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\http.py", line 680, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\http.py", line 959, in __call__
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\http.py", line 509, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\web\controllers\main.py", line 896, in call_button
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\web\controllers\main.py", line 884, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\modules\registry.py", line 385, in new
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\modules\loading.py", line 338, in load_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\modules\loading.py", line 237, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\modules\loading.py", line 123, in load_module_graph
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\modules\module.py", line 324, in load_openerp_module
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server.\openerp\modules\module.py", line 61, in load_module
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\fpoc__init__.py", line 3, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\fpoc\fiscal_printer.py", line 28, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\fpoc\controllers__init__.py", line 23, in <module>
  File "C:\Program Files (x86)\Odoo 9.0-20160223\server\openerp\addons\fpoc\controllers\main.py", line 30, in <module>
ImportError: No module named multiprocessing

No tengo idea que Python tengo instalado se instalo con Odoo

Gracias!
Saludos

**Comment by elgransan** [comment]
Aparentemente no es compatible con windows
https://www.odoo.com/fr_FR/forum/aide-1/question/multiprocessing-mode-in-windows-83307

Una consulta, las terminales que tengo instaladas son todas windows, tendré que pasarlas a linux para que funcione el controlador fiscal? 

Gracias!

**Comment by csrocha** [comment]
Si, multiprocessing no está disponible en windows. Igual, este módulo solo es para el servido, por lo tanto que lo necesitas para los puntos de ventas. En ellos deberías usar el fpoc-chrome (https://github.com/csrocha/fpoc-chrome).

**Comment by csrocha** [comment]
@elgransan , intenté de nuevo porque me parece raro el problema ya que la documentación de Python indica que funciona el módulo. Intentando de nuevo en un windows con Python 2.7.11 la importación del módulo funciona.
